# Generated by Django 4.1 on 2022-08-11 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('bar_code', models.CharField(max_length=20)),
                ('net_weight', models.CharField(max_length=10)),
                ('expiration_date', models.DateField()),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='notification_list',
            field=models.ManyToManyField(to='stock_api.product'),
        ),
    ]
