# Generated by Django 4.1 on 2022-08-11 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_api', '0002_product_user_notification_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='expiration_date',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='notification_list',
            field=models.ManyToManyField(blank=True, to='stock_api.product'),
        ),
    ]
